### ISSUE TITLE
Saved video file only has one video frame 

### ISSUE THREAD

**Issue by tom-wisnowski** [googlesamples/android-Camera2Video#24] opened 2016-03-06 18:40 UTC
Ran the sample on a Galaxy S6. The video file is saved, but when pulling the video file and playing it on the desktop it only has audio and 1 frame of video. The video appears to be frozen in playback. 

Any ideas? Perhaps the surface list is not getting updated correctly by the background handler in the capture session? The preview surface is updated correctly, just not the mediarecorder surface.

**Comment by tom-wisnowski** [comment] 2016-03-06 20:35
update. when I view the files saved on the device something weird happens. The audio plays completely and then the video animates after the audio completes. When you look at the video playback controls the video starts when it looks like the playback is at the end of the video. Could this be an issue with how I have setup the mediarecorder? I have repro'ed this on two devices.

**Comment by tom-wisnowski** [comment] 2016-03-07 05:58
If I do not configure the audio source on the media recorder then the video plays back as expected. Once I add the MIC source to the media encoder the problem appears.

**Comment by saurabharora90** [comment] 2016-05-03 04:52
I am having the same issue. @twisnowski did you manage to fix this?

**Comment by tom-wisnowski** [comment] 2016-05-06 19:33
@saurabharora90 Sorry, no fix. Do you still see the issue?

**Comment by saurabharora90** [comment] 2016-05-07 03:22
@twisnowski yes I still see it

**Comment by zeebone** [comment] 2016-06-02 14:41
I'm running into a similar issue with my Galaxy S7 Edge running Marshmallow.

I've got the Galaxy Tab S2 9.7 running Lollipop and it runs on that no problem. I've also tested on my Nexus 7 LTE running Marshmallow and it runs on that as well. 

I'm guessing this must be a limitation or some kind of change in the code that Samsung made with Touchwiz on the Marshmallow.

Has anyone had any luck getting this to work on their Samsung? I'm unable to even get the Mediarecorder to run through prepare if I try to omit the setting of the audiosource.

**Comment by cybaker** [comment] 2016-06-02 20:20
The issue is a deep sleep problem on some devices running Marshmallow. It appears to be CPU related as an S7 on Verizon doesn't have the issue, but an S7 on AT&T does have the issue. I've seen this on an S6 Verizon phone when it updated to Marshmallow.

In order to replicate, reboot a device while connected to USB. Run the sample. All should be ok. Then, disconnect the device, let it go into deep sleep (screen off, no movement for 5? minutes), and try again. The issue will appear once the device has gone into deep sleep.

The root cause is that the first sample of the recorded video has a duration that is ginormous, making the player believe the first frame should be displayed for a very long time, which is the symptom of it looking like just one frame of video. Use mp4parser and look at the video track's decodingTimes. You can see the difference from a good and bad decoding time in the attached files.

<img width="411" alt="screen shot 2016-06-02 at 7 32 06 am" src="https://cloud.githubusercontent.com/assets/1371616/15759608/4008138e-28c4-11e6-94fb-01a6ffac5125.png">
<img width="411" alt="screen shot 2016-06-02 at 7 51 37 am" src="https://cloud.githubusercontent.com/assets/1371616/15759609/400a7318-28c4-11e6-8987-32d91135ff97.png">

I understand this is a known issue in deep sleep but cannot find the issue quickly on google developers. I'm currently trying to use mp4parser to rewrite that one sample's duration, but I'm not an expert mp4parser guy.

**Comment by zeebone** [comment] 2016-06-02 20:28
Interesting. I tried doing the reboot and you are right, it worked like a charm. Really weird.

I may have to delve a little deeper...

Thanks for the insight!

**Comment by cybaker** [comment] 2016-06-03 21:25
Here is my workaround. For a 5 minute recording on an S6, it was about a 700MB mp4 file. This processing took about 20 seconds to read and rewrite that file:

```
        DataSource channel = new FileDataSourceImpl(rawFile);
        IsoFile isoFile = new IsoFile(channel);

        List<TrackBox> trackBoxes = isoFile.getMovieBox().getBoxes(TrackBox.class);
        boolean sampleError = false;
        for (TrackBox trackBox : trackBoxes) {
            TimeToSampleBox.Entry firstEntry = trackBox.getMediaBox().getMediaInformationBox().getSampleTableBox().getTimeToSampleBox().getEntries().get(0);

            // Detect if first sample is a problem and fix it in isoFile
            // This is a hack. The audio deltas are 1024 for my files, and video deltas about 3000
            // 10000 seems sufficient since for 30 fps the normal delta is about 3000
            if(firstEntry.getDelta() > 10000) {
                sampleError = true;
                firstEntry.setDelta(3000);
            }
        }

        if(sampleError) {
            Movie movie = new Movie();
            for (TrackBox trackBox : trackBoxes) {
                    movie.addTrack(new Mp4TrackImpl(channel.toString() + "[" + trackBox.getTrackHeaderBox().getTrackId() + "]" , trackBox));
            }
            movie.setMatrix(isoFile.getMovieBox().getMovieHeaderBox().getMatrix());
            Container out = new DefaultMp4Builder().build(movie);

            //delete file first!
            FileChannel fc = new RandomAccessFile(rawFile.getName(), "rw").getChannel();
            out.writeContainer(fc);
            fc.close();
            Log.d(TAG, "Finished correcting raw video");
        } 
```

**Comment by OptimusDan** [comment] 2016-06-22 10:38
I've also come across the same issue, glad to see it's not just me! The fix above worked great for me, however I need the recorded video to be played on some older device's HTML video elements (which don't support the ISO type, just plain old MP4s).

I'm wondering @cybaker , as you mentioned the initial 'deep sleep' problem, if you had any further insight into what's actually causing the problem? How did you come to the conclusion? Is there anything low level that can be accessed to analyse/control this behaviour? i.e, is there a way to "kick" the device and media recorder out of this glitchy state?

**Comment by time007** [comment] 2016-06-24 06:56
I am having the same issue too..so sad!!,ony on Samsung S6

**Comment by yurii-diachenko** [comment] 2016-08-08 08:37
Any update on this issue?

**Comment by kishorejethava** [comment] 2016-10-20 08:40
@cybaker getting **NPA** function getMovieBox() on line

`List<TrackBox> trackBoxes = isoFile.getMovieBox().getBoxes(TrackBox.class);`

**Comment by jaydeep82** [comment] 2016-10-26 06:37
I'm getting same issue in both S6 and S7. 
Video has complete audio but 1 frame of video. It appears to be frozen in playback.

Any solution about this ? is google team or other team working on it to fix it ?

thank you.

**Comment by PeakerChen** [comment] 2016-11-22 07:44
@cybaker Can you tell me what tool you using to parser MP4.

**Comment by blackvirus18** [comment] 2016-12-27 09:26
I am also getting the same issue, is there are any fix for this, getting this on my production application.

**Comment by adneerav** [comment] 2017-01-24 05:57
Hello

I am also facing the same issue for all samsung devices.

I also tried [this](https://github.com/googlesamples/android-Camera2Video/issues/24#issuecomment-223698486) given by @cybaker but the same issue which is mentioned in comment .

Apart from the above also tried below things using mp4 parser but still the issue is not resolved.(7 seconds track converted to more thn 30 mnts by trying below things and given by @cybaker )

1. Extracted audio track from video
2. Extracted video track from video
3. Merged Video And Audio 

If anyone can get solutions please post it.

Thanks

**Comment by luca992** [comment] 2017-04-05 01:16
My Verizon Galaxy S7 Edge on 7.0 has the same issue.

**Comment by maxchehab** [comment] 2017-04-12 06:05
Has anyone been able to find a solution?

**Comment by edigitalandroiddeveloper** [comment] 2017-04-18 05:56
I run android-Camera2Video in s6 and s7 video recorded and save in sdcard. but when we preview the saved  video then video freeze but sound played. Kindly let me know what is the solution for given devices.

**Comment by RockyLin** [comment] 2017-05-25 10:36
F**k Samsung!

**Comment by opannapo** [comment] 2017-08-22 14:43
Can't playing video frames but good on audio result.
Video frames only running after audio playing completed.

To make this sample running fine, i must restart my phone before.
Confused :(

**Comment by liamdo12** [comment] 2017-08-29 07:17
@cybaker I've tried your solution and it works. Thanks a lot

**Comment by pablogeek** [comment] 2018-01-26 10:49
This is still happening, is there any other way we can fix it without using mp4 parser?

**Comment by pablogeek** [comment] 2018-02-07 12:22
@cybaker I have tried your solution but still not working. Is this gonna be solved at some point?

**Comment by pablogeek** [comment] 2018-02-08 10:21
@cybaker Seems mp4parser is removing the MPEG header, it is the only difference I can see between the original file and the one generated with your code.

**Comment by pablogeek** [comment] 2018-02-08 10:53
This is before I convert the file
<img width="699" alt="screen shot 2018-02-08 at 09 47 36" src="https://user-images.githubusercontent.com/1773546/35969248-2303953a-0cbe-11e8-862a-61635df3563f.png">

This is after:
<img width="695" alt="screen shot 2018-02-08 at 10 52 26" src="https://user-images.githubusercontent.com/1773546/35969256-2d24c868-0cbe-11e8-9c77-7a9c63e8620c.png">

**Comment by ryanfoo** [comment] 2018-02-13 04:39
Huh I also I encountered this issue on my S7. It was weird because I was running the same code I uploaded on it days prior to the error. Then resetting the phone (not a hard reset) got rid of the issue.

So so very confused

**Comment by cybaker** [comment] 2018-04-13 18:29
Hi everyone:

Lots of questions and I've been off that project for two years. I believe it to be only a Samsung issue as it doesn't happen on other manufacturer phones I was testing like LG, Motorola, and Google Pixels, something to do with their recording software using the wrong real time counter. Android now has multiple real time clocks and if the device ever deep sleeps even once the clocks will differ by the deep sleep amount. There's plenty of documentation about it in Android Alarms so check it out if you need more info. It is for Samsung to fix and maybe they have in their own video playback software without fixing the recording side. That is too bad for us developers.

My fix above is still working as far as I know. I'm out of that company and don't have access to the particular version of mp4parser but I believe it was up to date 2 years ago. All that needs to be done is rewrite the duration of that first frame and the issue is solved, but in order to do that it is easiest to read in the entire file and rewrite but it takes time with a video file.

I wish you all luck with Samsung as they touch so many OS parts.

**Comment by fl-eric** [comment] 2018-06-05 21:07
This issue is also present on my Samsung J5 Prime (SM-G570M) running Android platform 7.0 Nougat (API 24). The bug can be reproduced by following the steps pointed by @cybaker

**Comment by LWChris** [comment] 2018-06-17 06:44
I had the same issue with a Samsung J5. While I can't fix the record side, at least I was able to restore the video using [ffmpeg](https://www.ffmpeg.org/download.html) and these command line options:

Windows: `.\ffmpeg.exe -i "broken.mp4" -vf setpts=N/FRAME_RATE/TB "fixed.mp4"`
Unix: `ffmpeg -i "broken.mp4" setpts=N/FRAME_RATE/TB "fixed.mp4"`

To be perfectly honest, I have NO idea what setting the presentation timestamps means, but it fixed the video for me. (Note: if your frame rate is not fixed, replace `FRAME_RATE` with the target frame rate, like `30` for example.)

**Comment by mukeshsolanki** [comment] 2018-07-24 22:27
@kishorejethava were you able to fix the **NPE**?

**Comment by cybaker** [comment] 2018-09-10 14:43
FYI the presentation timestamp is how long the video frame is presented to the screen, how long it is shown on screen until the next frame. Frames should normally be presented around 33 msec for a 30 frames per second recording. In the Samsung error case, the first frame's timestamp is huge (in my example 88813322 instead of about 3000). So for that error the first frame of the video will be presented to the screen for a duration of about 8881 times longer than normal. That is why playing the video seems to be stuck, the first frame is shown on the screen for a really long time instead of the usual 1/30th of a second. The audio continues playing because it's a different decoding stream.

**Comment by bsrirangaswamy** [comment] 2018-09-26 05:45
A short term temporary fix is to use Camera API (I know it it deprecated) to record videos instead of Camera2. It worked for me.

**Comment by koushick123** [comment] 2018-10-14 12:13
I had the same issue. I was using Camera 1 API and configured audio source to use CAMCORDER, the video would appear frozen. When I changed the audio source to MIC, the video and audio play correctly.

People who are using camera 1 API, can try this solution.

**Comment by xhanix** [comment] 2018-12-17 20:59
@cybaker try waking up the cpu with PowerManager (PARTIAL flag) before starting the capture. I am using the Camera2 API and your initial post helped me figure out this issue on Galaxy S7. The power lock solved my problem and my other android devices have become a lot more responsive too. Don't forget to release the lock after done recording.

[Docs: https://developer.android.com/training/scheduling/wakelock]
PowerManager powerManager = (PowerManager) getSystemService(POWER_SERVICE);
WakeLock wakeLock = powerManager.newWakeLock(PowerManager.PARTIAL_WAKE_LOCK,
        "MyApp::MyWakelockTag");
wakeLock.acquire();

**Comment by einsteinarbert** [comment] 2019-03-01 03:30
Anyone has good solution directly in java Android code?

**Comment by andreififiita** [comment] 2019-04-08 11:49
I am also looking for a solution. It should be pretty simple, since many other video recording apps (like instagram or other camera apps) work without a problem.

**Comment by MarekWaszczuk** [comment] 2019-08-27 13:31
What helped me on Samsung A7 in that situation was changing the:
            setAudioEncoder(MediaRecorder.AudioEncoder.AAC)
to
            setAudioEncoder(MediaRecorder.AudioEncoder.DEFAULT)

when setting up the mediaRecording.

**Comment by codingjeremy** [comment] 2019-09-19 22:35
This sample has been migrated to a new location where we can accept Pull Requests (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories

**Closed as completed by codingjeremy** 2019-09-19 22:35 UTC
