### ISSUE TITLE
Full Screen preview and record.

### ISSUE THREAD

**Issue by ShagunParikh** [googlesamples/android-Camera2Video#58] opened 2017-08-18 04:53 UTC
I could not find a way to make the preview and recording of the video full screen. The default Camera App of motorola and samsung has a full screen previews. 

Hence, these demo should also have the full screen preview without view getting stretched. Please help.

**Comment by pablogeek** [comment] 2017-09-28 08:29
@ShagunParikh Any solution?

**Comment by amlan-routray** [comment] 2018-01-16 16:03
Using frame layout around the autofittextureview solved the issue in my case. The video preview is not fullscreen but it maintains aspect ratio. And talking of full screen default camera app. You may notice that on changing the resolution you will miss out the full screen.

**Comment by Chandu1233** [comment] 2018-06-14 02:01
Hi @ShagunParikh @pablogeek I am also facing same issue now, could you please let me know if there is any solution found.

@amlan-routray thanks for the valuable comment, the issue is only when dealing with devices with low resolution.

Found a workaround in the below link. 
https://stackoverflow.com/questions/39044494/get-full-screen-preview-with-android-camera2

**Comment by codingjeremy** [comment] 2019-09-19 22:38
This sample has been migrated to a new location where we can accept Pull Requests (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories

**Closed as completed by codingjeremy** 2019-09-19 22:38 UTC
